import "./globals.scss";
import { ContextProvider } from "@/components/client/clientComponent";

export const metadata = {
  title: "Anontalks",
  description: "Generated by Anontalks",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>
        <ContextProvider>{children}</ContextProvider>
      </body>
    </html>
  );
}
